####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from router import Router
import heapq
from packet import Packet
import time
import json


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        self.seq_num = 0
        self.neighbors = {}  # {port: (neighbor, cost)}
        self.link_state_db = {}  # {router_addr: (seq_num, [(neighbor, cost), ...])}
        self.forwarding_table = {}  # {dest: port}


    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            pass

    def handle_new_link(self, port, endpoint, cost):
        self.neighbors[port] = (endpoint, cost)
        self.seq_num += 1
        self.link_state_db[self.addr] = (
            self.seq_num,
            [(ep, c) for _, (ep, c) in self.neighbors.items()]
        )
        print(f"[DEBUG] {self.addr} thêm link tới {endpoint} với cost {cost}")
        self.flood()
        self.recompute_paths()

    def handle_remove_link(self, port):
        if port in self.neighbors:
            del self.neighbors[port]
            self.seq_num += 1
            self.link_state_db[self.addr] = (
                self.seq_num,
                [(ep, c) for _, (ep, c) in self.neighbors.items()]
            )
            print(f"[DEBUG] {self.addr} xóa link trên port {port}")
            self.flood()
            self.recompute_paths()

    def handle_time(self, time_ms):
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            self.flood()

    def recompute_paths(self):
        print(f"[DEBUG] recompute_paths() được gọi bởi router {self.addr}")
        graph = {}
        for router, (_, links) in self.link_state_db.items():
            graph[router] = {neighbor: cost for neighbor, cost in links}

        dist = {self.addr: 0}
        prev = {}
        visited = set()
        heap = [(0, self.addr)]

        while heap:
            cost, node = heapq.heappop(heap)
            if node in visited:
                continue
            visited.add(node)

            for neighbor, weight in graph.get(node, {}).items():
                new_cost = cost + weight
                if neighbor not in dist or new_cost < dist[neighbor]:
                    dist[neighbor] = new_cost
                    prev[neighbor] = node
                    heapq.heappush(heap, (new_cost, neighbor))

        self.forwarding_table.clear()
        for dest in dist:
            if dest == self.addr:
                continue
            # Truy vết đường đi để tìm next hop
            next_hop = dest
            while prev[next_hop] != self.addr:
                next_hop = prev[next_hop]
            for p, (ep, _) in self.neighbors.items():
                if ep == next_hop:
                    self.forwarding_table[dest] = p
                    break


    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr}, neighbors={list(self.neighbors.values())})"
